#!/usr/bin/env python3

import os, sys, svgwrite
from PyQt5.QtCore import QFileSystemWatcher
from PyQt5.QtSvg import QSvgWidget
from PyQt5.QtWidgets import QApplication, QWidget

class MainWindow(QWidget):
    def __init__(self, path):
        super().__init__()
        self.path = path
        self.palette = QSvgWidget(parent=self)
        self.palette.setGeometry(10, 10, 1080, 1080)
        self.palette.load(self.path)
        self.file_watcher = QFileSystemWatcher()
        self.file_watcher.fileChanged.connect(self.palette.load)
        self.file_watcher.addPaths([self.path])
        self.palette.load(self.path)

if __name__ == "__main__":
    app = QApplication([])
    try:
        path = sys.argv[1]
        assert os.path.exists(path) # you cannot start with an nonexistent file; QT limitation.
    except:
        print("Usage: %s <path_to_svg_file>" % os.path.basename(__file__), file=sys.stderr)
        sys.exit(1)
    window = MainWindow(path)
    window.show()
    app.exec()
